package com.cognizant.countryservice.config;

import com.cognizant.countryservice.entity.Country;
import com.cognizant.countryservice.repository.CountryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

/**
 * Data initialization component to populate country data
 */
@Component
public class DataInitializer implements CommandLineRunner {
    
    @Autowired
    private CountryRepository countryRepository;
    
    @Override
    public void run(String... args) throws Exception {
        // Clear existing data
        countryRepository.deleteAll();
        
        // Populate country data
        insertCountryData();
        
        System.out.println("Country data initialized successfully!");
        System.out.println("Total countries loaded: " + countryRepository.count());
    }
    
    private void insertCountryData() {
        // Insert all countries as provided in the requirement
        countryRepository.save(new Country("AF", "Afghanistan"));
        countryRepository.save(new Country("AL", "Albania"));
        countryRepository.save(new Country("DZ", "Algeria"));
        countryRepository.save(new Country("AS", "American Samoa"));
        countryRepository.save(new Country("AD", "Andorra"));
        countryRepository.save(new Country("AO", "Angola"));
        countryRepository.save(new Country("AI", "Anguilla"));
        countryRepository.save(new Country("AQ", "Antarctica"));
        countryRepository.save(new Country("AG", "Antigua and Barbuda"));
        countryRepository.save(new Country("AR", "Argentina"));
        countryRepository.save(new Country("AM", "Armenia"));
        countryRepository.save(new Country("AW", "Aruba"));
        countryRepository.save(new Country("AU", "Australia"));
        countryRepository.save(new Country("AT", "Austria"));
        countryRepository.save(new Country("AZ", "Azerbaijan"));
        countryRepository.save(new Country("BS", "Bahamas"));
        countryRepository.save(new Country("BH", "Bahrain"));
        countryRepository.save(new Country("BD", "Bangladesh"));
        countryRepository.save(new Country("BB", "Barbados"));
        countryRepository.save(new Country("BY", "Belarus"));
        countryRepository.save(new Country("BE", "Belgium"));
        countryRepository.save(new Country("BZ", "Belize"));
        countryRepository.save(new Country("BJ", "Benin"));
        countryRepository.save(new Country("BM", "Bermuda"));
        countryRepository.save(new Country("BT", "Bhutan"));
        countryRepository.save(new Country("BO", "Bolivia, Plurinational State of"));
        countryRepository.save(new Country("BQ", "Bonaire, Sint Eustatius and Saba"));
        countryRepository.save(new Country("BA", "Bosnia and Herzegovina"));
        countryRepository.save(new Country("BW", "Botswana"));
        countryRepository.save(new Country("BV", "Bouvet Island"));
        countryRepository.save(new Country("BR", "Brazil"));
        countryRepository.save(new Country("IO", "British Indian Ocean Territory"));
        countryRepository.save(new Country("BN", "Brunei Darussalam"));
        countryRepository.save(new Country("BG", "Bulgaria"));
        countryRepository.save(new Country("BF", "Burkina Faso"));
        countryRepository.save(new Country("BI", "Burundi"));
        countryRepository.save(new Country("KH", "Cambodia"));
        countryRepository.save(new Country("CM", "Cameroon"));
        countryRepository.save(new Country("CA", "Canada"));
        countryRepository.save(new Country("CV", "Cape Verde"));
        countryRepository.save(new Country("KY", "Cayman Islands"));
        countryRepository.save(new Country("CF", "Central African Republic"));
        countryRepository.save(new Country("TD", "Chad"));
        countryRepository.save(new Country("CL", "Chile"));
        countryRepository.save(new Country("CN", "China"));
        countryRepository.save(new Country("CX", "Christmas Island"));
        countryRepository.save(new Country("CC", "Cocos (Keeling) Islands"));
        countryRepository.save(new Country("CO", "Colombia"));
        countryRepository.save(new Country("KM", "Comoros"));
        countryRepository.save(new Country("CG", "Congo"));
        countryRepository.save(new Country("CD", "Congo, the Democratic Republic of the"));
        countryRepository.save(new Country("CK", "Cook Islands"));
        countryRepository.save(new Country("CR", "Costa Rica"));
        countryRepository.save(new Country("HR", "Croatia"));
        countryRepository.save(new Country("CU", "Cuba"));
        countryRepository.save(new Country("CW", "Curaçao"));
        countryRepository.save(new Country("CY", "Cyprus"));
        countryRepository.save(new Country("CZ", "Czech Republic"));
        countryRepository.save(new Country("CI", "Côte d'Ivoire"));
        countryRepository.save(new Country("DK", "Denmark"));
        countryRepository.save(new Country("DJ", "Djibouti"));
        countryRepository.save(new Country("DM", "Dominica"));
        countryRepository.save(new Country("DO", "Dominican Republic"));
        countryRepository.save(new Country("EC", "Ecuador"));
        countryRepository.save(new Country("EG", "Egypt"));
        countryRepository.save(new Country("SV", "El Salvador"));
        countryRepository.save(new Country("GQ", "Equatorial Guinea"));
        countryRepository.save(new Country("ER", "Eritrea"));
        countryRepository.save(new Country("EE", "Estonia"));
        countryRepository.save(new Country("ET", "Ethiopia"));
        countryRepository.save(new Country("FK", "Falkland Islands (Malvinas)"));
        countryRepository.save(new Country("FO", "Faroe Islands"));
        countryRepository.save(new Country("FJ", "Fiji"));
        countryRepository.save(new Country("FI", "Finland"));
        countryRepository.save(new Country("FR", "France"));
        countryRepository.save(new Country("GF", "French Guiana"));
        countryRepository.save(new Country("PF", "French Polynesia"));
        countryRepository.save(new Country("TF", "French Southern Territories"));
        countryRepository.save(new Country("GA", "Gabon"));
        countryRepository.save(new Country("GM", "Gambia"));
        countryRepository.save(new Country("GE", "Georgia"));
        countryRepository.save(new Country("DE", "Germany"));
        countryRepository.save(new Country("GH", "Ghana"));
        countryRepository.save(new Country("GI", "Gibraltar"));
        countryRepository.save(new Country("GR", "Greece"));
        countryRepository.save(new Country("GL", "Greenland"));
        countryRepository.save(new Country("GD", "Grenada"));
        countryRepository.save(new Country("GP", "Guadeloupe"));
        countryRepository.save(new Country("GU", "Guam"));
        countryRepository.save(new Country("GT", "Guatemala"));
        countryRepository.save(new Country("GG", "Guernsey"));
        countryRepository.save(new Country("GN", "Guinea"));
        countryRepository.save(new Country("GW", "Guinea-Bissau"));
        countryRepository.save(new Country("GY", "Guyana"));
        countryRepository.save(new Country("HT", "Haiti"));
        countryRepository.save(new Country("HM", "Heard Island and McDonald Islands"));
        countryRepository.save(new Country("VA", "Holy See (Vatican City State)"));
        countryRepository.save(new Country("HN", "Honduras"));
        countryRepository.save(new Country("HK", "Hong Kong"));
        countryRepository.save(new Country("HU", "Hungary"));
        countryRepository.save(new Country("IS", "Iceland"));
        countryRepository.save(new Country("IN", "India"));
        countryRepository.save(new Country("ID", "Indonesia"));
        countryRepository.save(new Country("IR", "Iran, Islamic Republic of"));
        countryRepository.save(new Country("IQ", "Iraq"));
        countryRepository.save(new Country("IE", "Ireland"));
        countryRepository.save(new Country("IM", "Isle of Man"));
        countryRepository.save(new Country("IL", "Israel"));
        countryRepository.save(new Country("IT", "Italy"));
        countryRepository.save(new Country("JM", "Jamaica"));
        countryRepository.save(new Country("JP", "Japan"));
        countryRepository.save(new Country("JE", "Jersey"));
        countryRepository.save(new Country("JO", "Jordan"));
        countryRepository.save(new Country("KZ", "Kazakhstan"));
        countryRepository.save(new Country("KE", "Kenya"));
        countryRepository.save(new Country("KI", "Kiribati"));
        countryRepository.save(new Country("KP", "Democratic People's Republic of Korea"));
        countryRepository.save(new Country("KR", "Republic of Korea"));
        countryRepository.save(new Country("KW", "Kuwait"));
        countryRepository.save(new Country("KG", "Kyrgyzstan"));
        countryRepository.save(new Country("LA", "Lao People's Democratic Republic"));
        countryRepository.save(new Country("LV", "Latvia"));
        countryRepository.save(new Country("LB", "Lebanon"));
        countryRepository.save(new Country("LS", "Lesotho"));
        countryRepository.save(new Country("LR", "Liberia"));
        countryRepository.save(new Country("LY", "Libya"));
        countryRepository.save(new Country("LI", "Liechtenstein"));
        countryRepository.save(new Country("LT", "Lithuania"));
        countryRepository.save(new Country("LU", "Luxembourg"));
        countryRepository.save(new Country("MO", "Macao"));
        countryRepository.save(new Country("MK", "Macedonia, the Former Yugoslav Republic of"));
        countryRepository.save(new Country("MG", "Madagascar"));
        countryRepository.save(new Country("MW", "Malawi"));
        countryRepository.save(new Country("MY", "Malaysia"));
        countryRepository.save(new Country("MV", "Maldives"));
        countryRepository.save(new Country("ML", "Mali"));
        countryRepository.save(new Country("MT", "Malta"));
        countryRepository.save(new Country("MH", "Marshall Islands"));
        countryRepository.save(new Country("MQ", "Martinique"));
        countryRepository.save(new Country("MR", "Mauritania"));
        countryRepository.save(new Country("MU", "Mauritius"));
        countryRepository.save(new Country("YT", "Mayotte"));
        countryRepository.save(new Country("MX", "Mexico"));
        countryRepository.save(new Country("FM", "Micronesia, Federated States of"));
        countryRepository.save(new Country("MD", "Moldova, Republic of"));
        countryRepository.save(new Country("MC", "Monaco"));
        countryRepository.save(new Country("MN", "Mongolia"));
        countryRepository.save(new Country("ME", "Montenegro"));
        countryRepository.save(new Country("MS", "Montserrat"));
        countryRepository.save(new Country("MA", "Morocco"));
        countryRepository.save(new Country("MZ", "Mozambique"));
        countryRepository.save(new Country("MM", "Myanmar"));
        countryRepository.save(new Country("NA", "Namibia"));
        countryRepository.save(new Country("NR", "Nauru"));
        countryRepository.save(new Country("NP", "Nepal"));
        countryRepository.save(new Country("NL", "Netherlands"));
        countryRepository.save(new Country("NC", "New Caledonia"));
        countryRepository.save(new Country("NZ", "New Zealand"));
        countryRepository.save(new Country("NI", "Nicaragua"));
        countryRepository.save(new Country("NE", "Niger"));
        countryRepository.save(new Country("NG", "Nigeria"));
        countryRepository.save(new Country("NU", "Niue"));
        countryRepository.save(new Country("NF", "Norfolk Island"));
        countryRepository.save(new Country("MP", "Northern Mariana Islands"));
        countryRepository.save(new Country("NO", "Norway"));
        countryRepository.save(new Country("OM", "Oman"));
        countryRepository.save(new Country("PK", "Pakistan"));
        countryRepository.save(new Country("PW", "Palau"));
        countryRepository.save(new Country("PS", "Palestine, State of"));
        countryRepository.save(new Country("PA", "Panama"));
        countryRepository.save(new Country("PG", "Papua New Guinea"));
        countryRepository.save(new Country("PY", "Paraguay"));
        countryRepository.save(new Country("PE", "Peru"));
        countryRepository.save(new Country("PH", "Philippines"));
        countryRepository.save(new Country("PN", "Pitcairn"));
        countryRepository.save(new Country("PL", "Poland"));
        countryRepository.save(new Country("PT", "Portugal"));
        countryRepository.save(new Country("PR", "Puerto Rico"));
        countryRepository.save(new Country("QA", "Qatar"));
        countryRepository.save(new Country("RO", "Romania"));
        countryRepository.save(new Country("RU", "Russian Federation"));
        countryRepository.save(new Country("RW", "Rwanda"));
        countryRepository.save(new Country("RE", "Réunion"));
        countryRepository.save(new Country("BL", "Saint Barthélemy"));
        countryRepository.save(new Country("SH", "Saint Helena, Ascension and Tristan da Cunha"));
        countryRepository.save(new Country("KN", "Saint Kitts and Nevis"));
        countryRepository.save(new Country("LC", "Saint Lucia"));
        countryRepository.save(new Country("MF", "Saint Martin (French part)"));
        countryRepository.save(new Country("PM", "Saint Pierre and Miquelon"));
        countryRepository.save(new Country("VC", "Saint Vincent and the Grenadines"));
        countryRepository.save(new Country("WS", "Samoa"));
        countryRepository.save(new Country("SM", "San Marino"));
        countryRepository.save(new Country("ST", "Sao Tome and Principe"));
        countryRepository.save(new Country("SA", "Saudi Arabia"));
        countryRepository.save(new Country("SN", "Senegal"));
        countryRepository.save(new Country("RS", "Serbia"));
        countryRepository.save(new Country("SC", "Seychelles"));
        countryRepository.save(new Country("SL", "Sierra Leone"));
        countryRepository.save(new Country("SG", "Singapore"));
        countryRepository.save(new Country("SX", "Sint Maarten (Dutch part)"));
        countryRepository.save(new Country("SK", "Slovakia"));
        countryRepository.save(new Country("SI", "Slovenia"));
        countryRepository.save(new Country("SB", "Solomon Islands"));
        countryRepository.save(new Country("SO", "Somalia"));
        countryRepository.save(new Country("ZA", "South Africa"));
        countryRepository.save(new Country("GS", "South Georgia and the South Sandwich Islands"));
        countryRepository.save(new Country("SS", "South Sudan"));
        countryRepository.save(new Country("ES", "Spain"));
        countryRepository.save(new Country("LK", "Sri Lanka"));
        countryRepository.save(new Country("SD", "Sudan"));
        countryRepository.save(new Country("SR", "Suriname"));
        countryRepository.save(new Country("SJ", "Svalbard and Jan Mayen"));
        countryRepository.save(new Country("SZ", "Swaziland"));
        countryRepository.save(new Country("SE", "Sweden"));
        countryRepository.save(new Country("CH", "Switzerland"));
        countryRepository.save(new Country("SY", "Syrian Arab Republic"));
        countryRepository.save(new Country("TW", "Taiwan, Province of China"));
        countryRepository.save(new Country("TJ", "Tajikistan"));
        countryRepository.save(new Country("TZ", "Tanzania, United Republic of"));
        countryRepository.save(new Country("TH", "Thailand"));
        countryRepository.save(new Country("TL", "Timor-Leste"));
        countryRepository.save(new Country("TG", "Togo"));
        countryRepository.save(new Country("TK", "Tokelau"));
        countryRepository.save(new Country("TO", "Tonga"));
        countryRepository.save(new Country("TT", "Trinidad and Tobago"));
        countryRepository.save(new Country("TN", "Tunisia"));
        countryRepository.save(new Country("TR", "Turkey"));
        countryRepository.save(new Country("TM", "Turkmenistan"));
        countryRepository.save(new Country("TC", "Turks and Caicos Islands"));
        countryRepository.save(new Country("TV", "Tuvalu"));
        countryRepository.save(new Country("UG", "Uganda"));
        countryRepository.save(new Country("UA", "Ukraine"));
        countryRepository.save(new Country("AE", "United Arab Emirates"));
        countryRepository.save(new Country("GB", "United Kingdom"));
        countryRepository.save(new Country("US", "United States"));
        countryRepository.save(new Country("UM", "United States Minor Outlying Islands"));
        countryRepository.save(new Country("UY", "Uruguay"));
        countryRepository.save(new Country("UZ", "Uzbekistan"));
        countryRepository.save(new Country("VU", "Vanuatu"));
        countryRepository.save(new Country("VE", "Venezuela, Bolivarian Republic of"));
        countryRepository.save(new Country("VN", "Viet Nam"));
        countryRepository.save(new Country("VG", "Virgin Islands, British"));
        countryRepository.save(new Country("VI", "Virgin Islands, U.S."));
        countryRepository.save(new Country("WF", "Wallis and Futuna"));
        countryRepository.save(new Country("EH", "Western Sahara"));
        countryRepository.save(new Country("YE", "Yemen"));
        countryRepository.save(new Country("ZM", "Zambia"));
        countryRepository.save(new Country("ZW", "Zimbabwe"));
        countryRepository.save(new Country("AX", "Åland Islands"));
    }
}
